controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    mecanum_drive_controller:
      ros__parameters:
        use_stamped_vel: false
        cmd_vel_timeout: 0.5
        base_frame_id: base_link

        wheel_separation_x: 0.192
        wheel_separation_y: 0.192
        wheel_radius: 0.0325

        front_left_wheel_command_joint_name: front_left_wheel_joint
        front_right_wheel_command_joint_name: front_right_wheel_joint
        rear_left_wheel_command_joint_name: rear_left_wheel_joint
        rear_right_wheel_command_joint_name: rear_right_wheel_joint

        front_left_wheel_state_joint_name: front_left_wheel_joint
        front_right_wheel_state_joint_name: front_right_wheel_joint
        rear_left_wheel_state_joint_name: rear_left_wheel_joint
        rear_right_wheel_state_joint_name: rear_right_wheel_joint

        command_interfaces:
          - velocity
        state_interfaces:
          - velocity

    velocity_controllers:
      ros__parameters:
        joints:
          - front_left_wheel_joint
          - front_right_wheel_joint
          - rear_left_wheel_joint
          - rear_right_wheel_joint
        interface_name: velocity

